name: push PR image to quay.io
on:
  pull_request_target

env:
  ALLOWED_USERS: foo bar baz

jobs:
  push-image:
    name: push image
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.17']
    steps:
      - name: install make
        run: sudo apt-get install make
      - name: set up go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: validate user
        id: validate_user
        run: |
          echo "${{ github.event.pull_request_target }}"
          echo "${{ github.event.pull_request_target.user }}"
          echo "${{ github.event.pull_request_target.user.login }}"
          for user in "${{ env.ALLOWED_USERS}}"; do
            if [[ "${{ github.event.pull_request_target.user.login }}" == "$user" ]]; then
                echo "$user is a known user, proceeding to build."
                exit 0
            fi
          done
          echo "User ${{ github.event.pull_request_target.user.login }} is unknown, PR image build canceled."
          exit 1
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: get short sha
        id: shortsha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: outcome
        run: echo "Building with SHA ${{ steps.shortsha.outputs.short_sha }}"
